- .github/ISSUE_TEMPLATE/bug.md
> feat(github): init bug issue template

- .github/ISSUE_TEMPLATE/bug.md
- pkg/scheduler/scheduler.go
- pkg/service/repository/repository.go
- pkg/store/repository/repository.go
- pkg/store/repository/repository_test.go
> feat: Adding repository cleanup before fetching new releases

- pkg/service/repository/repository.go
> feat: Adding name cleaning if full url is provided

- pkg/renderer/ketchups.go
> fix: Using created ketchup output for accurate confirm msg

- .github/dependabot.yml
- *List steps to help reviewers*
- #IssueNumber
> refactor: Migrating to github dependabot

- pkg/github/github.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- *List steps to help reviewers*
- #IssueNumber
> test: Testing newReleases loop

- .travis.yml
- go.mod
> chore(deps): Bumping to go1.15

- pkg/renderer/app_test.go
- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
> test: Improve coverage of repository package

- pkg/renderer/public.go
- pkg/renderer/renderer_test.go
- templates/index.html
- templates/signup.html
- templates/suggest.html
> feat: Adding basic feature for homepage

- templates/signup.html
> feat: Adding placeholder for indicating type of answer

- cmd/ketchup/api.go
- go.mod
- go.sum
- infra/config.yaml
- pkg/scheduler/scheduler.go
> ci: Switching to amqp mailer

- go.mod
- go.sum
> chore(deps): Bumping mailer for fixing enabled bug

- go.mod
- go.sum
> chore(deps): Bumping httputils to fix redirect error

- templates/index.html
- templates/ketchup.html
- templates/suggest.html
> feat(a11y): Changing white color for better contrast

- templates/index.html
- templates/ketchup.html
- templates/suggest.html
> revert: feat(a11y): Reverting white smoke color change

- templates/index.html
> feat(a11y): Changing colors for a11y compliance

- go.mod
> chore(deps): Bumping mailer for having starting log

- go.mod
- infra/config.yaml
> Charts bump

- infra/config.yaml
> chore(deps): Bumping postgres charts

- go.mod
- go.sum
> chore(deps): Bumping mailer

- go.mod
- go.sum
- pkg/github/github.go
- pkg/helm/helm.go
- pkg/scheduler/scheduler.go
- pkg/semver/semver.go
- pkg/semver/semver_test.go
> feat(semver): Handling suffix for alpha, beta etc.

- pkg/ketchup/ketchups.go
- pkg/model/ketchup.go
- pkg/model/repository.go
- pkg/model/repository_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/service/ketchup/ketchup.go
- pkg/service/ketchup/ketchup_test.go
- pkg/service/ketchup/ketchuptest/ketchuptest.go
- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
- pkg/service/repository/repositorytest/repositorytest.go
- pkg/store/ketchup/ketchup.go
- pkg/store/ketchup/ketchup_test.go
- pkg/store/repository/repository.go
- pkg/store/repository/repository_test.go
- pkg/store/repository/repository_version.go
- sql/ddl.sql
- sql/migration_2020-01-22_1.sql
- sql/migration_2020-01-22_2.sql
- templates/ketchup.html
- templates/suggest.html
> feat(repository): Adding possibility to handle multiple versions

- pkg/store/repository/repository_test.go
- pkg/store/repository/repository_version.go
- pkg/store/repository/repository_version_test.go
> test(repository): Increasing test coverage for repository store

- pkg/github/github.go
- pkg/github/githubtest/githubtest.go
- pkg/helm/helm.go
- pkg/scheduler/scheduler.go
- pkg/semver/semver.go
- pkg/semver/semver_test.go
- pkg/service/repository/repository.go
- pkg/service/repository/repositorytest/repositorytest.go
> test(ketchup): Adding pattern matching for getting latest version

- .github/workflows/codeql-analysis.yml
> ci(codeql): Fixing CodeQL analysis for Golang

- pkg/github/github.go
- pkg/github/githubtest/githubtest.go
- pkg/helm/helm.go
- pkg/model/ketchup.go
- pkg/model/ketchup_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/service/ketchup/ketchup.go
- pkg/service/repository/repository.go
- pkg/service/repository/repositorytest/repositorytest.go
- pkg/service/user/user.go
> feat(scheduler): Adding pattern handling for scheduler

- pkg/model/ketchup.go
- pkg/model/ketchup_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/service/ketchup/ketchup.go
- pkg/service/ketchup/ketchuptest/ketchuptest.go
- pkg/store/repository/repository_version.go
> fix(repository): Fixing update of repository versions

- pkg/store/repository/repository_version.go
> fix(repository): Fixing update of the version

- pkg/scheduler/scheduler_test.go
- pkg/service/ketchup/ketchup_test.go
- pkg/service/ketchup/ketchuptest/ketchuptest.go
- pkg/service/repository/repositorytest/repositorytest.go
> refactor(scheduler): Changing stub to mock for scheduler dependencies

- pkg/github/githubtest/githubtest.go
- pkg/service/ketchup/ketchup.go
- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
- pkg/service/repository/repositorytest/repositorytest.go
> refactor(repository): Removing hardcoded references to DefaultPattern

- pkg/ketchup/ketchups.go
- pkg/model/repository.go
- pkg/scheduler/scheduler_test.go
- pkg/service/ketchup/ketchup_test.go
- pkg/service/ketchup/ketchuptest/ketchuptest.go
- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
- pkg/service/repository/repositorytest/repositorytest.go
- pkg/store/ketchup/ketchup.go
- pkg/store/ketchup/ketchup_test.go
- pkg/store/repository/repository.go
- pkg/store/repository/repository_test.go
- pkg/store/repository/repository_version_test.go
> refactor(ketchup): Moving from stuck to mock for ketchup service test

- pkg/ketchup/ketchups.go
- pkg/model/ketchup.go
- pkg/model/ketchup_test.go
- pkg/service/ketchup/ketchup_test.go
- pkg/store/ketchup/ketchup.go
> refactor(ketchup): Using New instead of direct instance creation

- pkg/semver/semver.go
- pkg/semver/semver_test.go
- pkg/service/ketchup/ketchup.go
- pkg/store/ketchup/ketchup.go
- pkg/store/ketchup/ketchup_test.go
- templates/ketchup.html
> feat(ketchup): Adding pattern input in UI

- sql/ddl.sql
> fix(sql): Adding ON DELETE CASCADE for dependent tables

- go.mod
- go.sum
- pkg/service/user/user_test.go
> refactor(user): Removing stuck in favor of mock usage

- pkg/github/github.go
- pkg/helm/helm.go
- pkg/model/semver.go
- pkg/scheduler/scheduler_test.go
- pkg/semver/pattern.go
- pkg/semver/pattern_test.go
- pkg/semver/semver.go
- pkg/semver/semver_test.go
- pkg/service/repository/repository_test.go
> Semver refactor

- go.sum
- pkg/service/ketchup/ketchup.go
- pkg/service/ketchup/ketchup_test.go
- pkg/store/ketchup/ketchup.go
- pkg/store/ketchup/ketchuptest/ketchuptest.go
> test(ketchup): Migrating from stuck to mock

- pkg/service/repository/repository_test.go
- pkg/store/repository/repository.go
- pkg/store/repository/repositorytest/repositorytest.go
> refactor(repository): Removing last stub in favor of mock

- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
> test(repository): Improving service test coverage

- .github/workflows/branch_clean.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/herodote.yml
- Makefile
- README.md
> ci: Changing default branch to main

- pkg/helm/helmtest/helmtest.go
- pkg/semver/pattern_test.go
- pkg/service/ketchup/ketchup.go
- pkg/service/ketchup/ketchup_test.go
- pkg/service/repository/repository_test.go
> test: Adding more test to improve coverage

- pkg/scheduler/scheduler.go
- pkg/service/repository/repository.go
- pkg/service/repository/repository_test.go
- pkg/store/repository/repository.go
- pkg/store/repository/repository_test.go
- pkg/store/repository/repositorytest/repositorytest.go
> fix: Fixing scheduler pattern matching and clean of old versions

- pkg/scheduler/scheduler_test.go
- pkg/semver/pattern_test.go
- pkg/service/ketchup/ketchup_test.go
- pkg/service/repository/repository_test.go
- pkg/service/user/user_test.go
- pkg/store/repository/repository_test.go
- pkg/store/user/user_test.go
> refactor: Removing some of the duplicates sonarcloud suggest

- go.sum
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/store/ketchup/ketchup_test.go
- pkg/store/repository/repository_test.go
- pkg/store/user/user_test.go
> refactor: Reudcing cyclomatic complexity for getNewReleases

- pkg/semver/semver.go
- pkg/semver/semver_test.go
Signed-off-by: Vincent Boutour <bob@vibioh.fr>
- #IssueNumber
> feat(semver): Adding support for long prefix for linkerd notably

- pkg/model/repository.go
- pkg/model/repository_test.go
- https://github.com/vibioh/ketchup/compare/v1.1.0...v1.0.0 => Empty
- https://github.com/vibioh/ketchup/compare/v1.0.0...v1.1.0 => Diff
N/A
> Fix compare

- cmd/ketchup/templates/ketchup.html
- Try to add new ketchup with empty text inputs (browser should prevent submit)
> fix(form): add required attribute to text inputs
